accounts/urls.py
from django.urls import path
# viewsモジュールをインポート
from . import views
from django.contrib.auth import views as auth_views

# URLパターンを逆引きできるように名前を付ける
app_name = 'accounts'

# URLパターンを登録するための変数
urlpatterns = [
    # サインアップページのビューの呼び出し
    #「http(s)://<ホスト名>/signup/」へのアクセスに対して、
    # viewsモジュールのSignUpViewをインスタンス化する
    path('signup/',
         views.SignUpView.as_view(),
         name = 'signup'),
    
    # サインアップ完了ページのビューの呼び出し
    # 「http(s)://<ホスト名>/signup_success/」へのアクセスに対して、
    # viewsモジュールのSignUpSuccessView.as_viewをインスタンス化する

    path('signup_success/',
         views.SignUpSuccessView.as_view(),
         name = 'signup_success'),

     # ログインページの表示
     #「http(s)://<ホスト名>signup/」へのアクセスに対して、
     # django.contrib.auth.views.LoginViewをインスタンス化して
     # ログインページを表示する
     path('login/',
          auth_views.LoginView.as_view(template_name = 'login.html'),
          name = 'login'
          ),

     # ログアウトを実行
     #「http(s)://<ホスト名>logout/」へのアクセスに対して、
     # django.contrib.auth.views.LogoutViewをインスタンス化して
     # ログアウトさせる
     path('logout/',
          auth_views.LogoutView.as_view(template_name = 'logout.html'),
          name = 'logout'
          ),
]

photo/urls.py
from django.urls import path
from . import views

#URLパターンを逆引きできるように名前を付ける
app_name = 'photo'

#URLパターンを登録する変数
urlpatterns = [
    #photoアプリへのアクセスはviewモジュールのIndexViewを実行
    path('', views.IndexView.as_view(), name='index'),

    #p446で追加
    #写真投稿ページへのアクセスはviewsモジュールのCreatePhotoViewを実行
    path('post/', views.CreatePhotoView.as_view(), name='post'),

    #p450で追加
    #投稿完了ページへのアクセスはviewsモジュールのPostSuccessViewを実行
    path('post_done/',
         views.PostSuccessView.as_view(),
         name='post_done'),
    
    # カテゴリ一覧ページ
    # photos/<Categorysテーブルのid値>にマッチング
    # <int:category>は辞書{category: id(int)}としてCategoryViewに渡される
    path('photos/<int:category>',
         views.CategoryView.as_view(),
         name = 'photos_cat'
        ),
    
    path('user-list/<int:user>',
        views.UserView.as_view(),
        name = 'user_list'
        ),

    #詳細ページ
    #photo-detail/<Photo Postsテーブルのid値>にマッチング
    #<int:pk>は辞書{pk: id(int)}としてDetailViewに渡される
    path('photo-detail/<int:pk>',
         views.DetailView.as_view(),
         name = 'photo_detail'
        ),
    
    # マイページ
    # mypage/へのアクセスはmypageViwを実行
    path('mypage/', views.MypageView.as_view(), name = 'mypage'),

    #URLを登録する変数

    #投稿写真の削除
    #photo/<Photo postsテーブルのid値>/delete/にマッチング
    #<int:pk>は{pk: id(int)}としてDetailViewに渡される
    path('photo/<int:pk>/delete/',
         views.PhotoDeleteView.as_view(),
         name = 'photo_delete'
        ),

]

photoproject/urls.py
from django.contrib import admin
from django.urls import path ,include
#from django.urls.conf import include #include追加

# auth.viewsをインポートしてauth_viewという名前で利用する
from django.contrib.auth import views as auth_views
#settingsを追加
from django.conf import settings
#staticを追加
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    
    #photo.urlsへのURLパターン
    path('', include('photo.urls')),

    path('', include('accounts.urls')),

    # パスワードリセットのためのURLパターン
    # PasswordResetConfigViewがプロジェクトのurls.pyを参照するのでここに記載
    # パスワードリセット申し込みページ
    path('password_reset/',
         auth_views.PasswordResetView.as_view(
             template_name = "password_reset.html"),
             name = 'password_reset'),
    
    # メール送信完了ページ
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name = "password_reset_sent.html"),
             name = 'password_reset_done'),
    
    # パスワードリセットページ
    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(
             template_name = "password_reset_form.html"),
             name = 'password_reset_confirm'),
    
    # パスワードリセット完了ページ
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name = "password_reset_done.html"),
             name = 'password_reset_complete'),
    
]

urlpatterns += static(
    #MEDIA_URL = 'media/'
    settings.MEDIA_URL,
    #MEDIA_ROOTにリダイレクト
    document_root=settings.MEDIA_ROOT
)

accounts/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    pass

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta:

        model = CustomUser

        fields = ('username','email','password1','password2')

accounts/views.py
from django.shortcuts import render
from django.views.generic import CreateView, TemplateView
from .forms import CustomUserCreationForm
from django.urls import reverse_lazy

class SignUpView(CreateView):
    '''サインアップページのビュー
    
    '''
    # forms.pyで定義したフォームのクラス
    form_class = CustomUserCreationForm
    # レンタリングするテンプレート
    template_name = "signup.html"
    # サインアップ完了後のリダイレクト先のURLパターン
    success_url = reverse_lazy('accounts:signup_success')

    def form_valid(self, form):
        '''CreateViewクラスのform_valid()をオーバーライド

        フォームのバリデーションを通過したときに呼ばれる
        フォームデータの登録を行う

        parameters:
            form(django.forms.Form):
                form_classに格納されているCustomUserCreationFormオブジェクト
        Return:
            HttpResponseRedirectオブジェクト:
                スーパークラスのform_valid()の戻り値を返すことで、
                success_urlで設定されているURLにリダイレクトさせる
        '''
        # formオブジェクトのフィールドの値をデータベースに保存
        user = form.save()
        self.object = user
        #　戻り値はスーパークラスのform_valid()の戻り値(HttpResponseRedirect)
        return super().form_valid(form)
    
class SignUpSuccessView(TemplateView):
        '''サインアップ完了ページのビュー

        '''
        # レンタリングするテンプレート
        template_name = "signup_success.html"

accounts/templates/login.html
{% load static %}
<!doctype html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>ログインページ</title>

    <link rel="icon" type="image/x-icon"
          href={% static 'assets/favicon.ico' %} />

    

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" 
            rel="stylesheet" 
            integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" 
            crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

    </style>

    
    <!-- Custom styles for this template -->
    <link href={%static "css/signin.css" %} rel="stylesheet">
  </head>
  <body class="text-center">
    
    <main class="form-signin">
     {% if form.errors %}
      <p style="color: red">ユーザーとパスワードが一致しません。</p>
     {% endif %}
      <form method="post">
        {% csrf_token %}
       <img class="mb-4" src={% static "img/めじろん.png" %} alt="めじろんのロゴ" width="100" height="auto">
       <h1 class="h3 mb-3 fw-normal">ログインしちょくれ！</h1>

       <label for="Username" class="visually_hidden">User name</label>
       <input type="text"
           name="username"
           id="id_username"
           maxlength="30"
           autocapitalize="none"
           autocomplete="username"
           class="form-control"
           placeholder="ユーザー名"
           required autofocus>
    
       <label for="Password" class="visually-hidden">
        Password</label>
    
       <input type="password"
           name="password"
           id="id_password"
           autocomplete="current-password"
           class="form-control"
           placeholder="パスワード"
           required autofocus>
    
        <input class="w-100 btn btn-lg btn-primary" 
           type="submit"
           value="ログイン">

       <br><br>
       <p><a href="{% url 'password_reset' %}">パスワードを忘れましたか？</a><p>
       <input type="hidden"
             name="next"
             value="{% url 'photo:index' %}">
           
      </form>
    </main>


    
  </body>
</html>

accounts/templates/logout.html
<!--ベーステンプレートを適用する-->
{% extends 'base.html' %}
<!--ヘッダー情報のページタイトルを設定する-->
{% block title %}ログアウトページ{% endblock %}

    {% block contents %}
    {% load static %}
    <!--Bootstrapのグリッドシステム-->
    <div class="container">
        <!--行を配置-->
        <div class="row">
            <!-- 列の左右に余白offset-4を入れる　列の上下パディングはpy-4-->
            <div class="col offset-4 py-4">

            <h3>ログアウトしました</h3>
            <!--トップページのリンクテキスト-->
            <p><a href="{% url 'photo:index'%}"><img src={% static "img/トップページに戻る.svg" %} alt="トップページに戻るボタン" width="150" height="40"></a><p>
    {% endblock %}

accounts/templates/password_reset.html
<!--ベーステンプレートを適応する-->
{% extends 'base.html' %}
<!--ヘッダー情報のページタイトルを設定する-->
{% block title %}Reset password{% endblock %}

    {% block contents %}
    <!--Bootstrapのグリッドシステム-->
    <div class="container">
        <!--行を配置-->
        <div class="row">
            <!--列の上下パディングはpy-4-->
            <div class="col py-4">
                <hr>
                <h3>パスワードをリセットしますか？</h3>
                <p>
                    登録済みのメールアドレスを入力してください。
                    パスワードリセットのリンクを記載したメールをすぐにお届けします。
                </p>
                <br>
                <!--メール送信のためのフォームを配置-->
                <form action=""method="POST" class="text-center">
                    {% csrf_token %}
                    <!--formに格納されているインプットボックスとラベルを出力-->
                    {{form}}
                    <!--送信ボタン-->
                    <input type="submit" value="メールを受け取る" /><br>
                </form>
                <br>
                <hr>
            </div>
        </div>
    </div>
    {% endblock %}

accounts/templates/password_reset_done.html
<!doctype html>
<html lang="ja">
    <head>
        <style>
            .pad{
                background-color: lavender;
                border: solid 2px;
                padding-top: 30px;
                padding-bottom: 50px;
                padding-left: 100px;
                margin-top: 50px;
                margin-right: 70px;
                margin-left: 70px;
            }
        </style>
    </head>

    <body>
        <div class="pad">
            <h2>パスワードがリセットされました。</h2>
            <p>
                Your password has been set. You may go ahead and login
            </p>
            <br>
            <a href="{% url 'photo:index' %}">Photo Galleryのトップページへ</a>
        </div>
    </body>
</html>

accounts/templates/password_reset_form.html
<!doctype html>
<html lang="ja">
    <head>
        <!--マージン、パディング、背景色を設定するCSSを定義-->
        <style>
        .pad{
            background-color: lavender;
            border: solid 2px;
            padding-top: 30px;
            padding-bottom: 50px;
            padding-left: 100px;
            margin-top: 50px;
            margin-right: 70px;
            margin-left: 70px;
        }
        </style>
    </head>

    <body>
        <div class="pad">
            <h2><font face = "Comic Sans MS";>Oitagram</font></h2>
            <h4>
                新しいパスワードを2回入力してください。これにより、正しく入力できたことが確認されます。
            </h4>
            <br \>
            <!--フォームを配置-->
            <form action="" method="POST">
                {% csrf_token %}
                <!--formに格納されている要素をすべて出力-->
                {{form}}
                <!--パスワードリセットボタン-->
                <input type="submit" value="パスワードリセット"/>
            </form>
        </div>
    </body>
</html>

accounts/templates/password_reset_sent.html
{% extends 'base.html' %}
{% block title %}パスワードリセットの送信{% endblock %}

        {% block contents %}
        <hr>
        <div class="container">
            <div class="row">
                <div class="col offset-2 py-4">
                    <h5>パスワードのリセット手順をメールで送信しました。
                        メールはすぐに届きます。</h5>
                    <br>
                    <h6>
                      メールが届かない場合は、登録済みのメールアドレスであるかを
                      確認し、迷惑メールフォルダーも確認してみてください。</h6>
                    <br>

                </div>
            </div>
        </div>
        {% endblock %}


accounts/templates/signup.html
<!--　ベーステンプレートを適用する-->
{% extends 'base.html'%}
<!--　ヘッダー情報のページタイトルを設定する-->
{% block title %}Sign up{% endblock %}

    {% block contents %}
    <!-- Bootatrapのグリッドシステム-->
    <br>
    <div class = "container">
        <!--行を配置-->
        <div class = "row">
            <!--列の左右に余白offset-2を入れる-->
            <div class ="col offset-2">
                <h3>サインアップ</h3>
                <!--サインアップのフォームを配置-->
                <form method = "post">
                    {% csrf_token %}
                    <!--formからフィールドを取り出す-->
                    {% for field in form %}
                    <p>
                        <!--ラベルを出力-->
                        {{ field.label_tag}}<br>
                        <!-- 入力文字数の制限 -->
                        {% if field.help_text != "この項目は必須です。半角アルファベット、半角数字、@/./+/-/_ で150文字以下にしてください。" %}
                        {{ field }}
                        {% endif %}
        
                        {% if field.help_text == "この項目は必須です。半角アルファベット、半角数字、@/./+/-/_ で150文字以下にしてください。" %}
                        <input type="text" name="username" maxlength="30" autofocus="" required="" id="id_username">
                        {% endif %}

                        <!-- help_textを出力-->
                        {% if field.help_text %}
                            {% if field.help_text != "この項目は必須です。半角アルファベット、半角数字、@/./+/-/_ で150文字以下にしてください。" %}
                            <small style="color: grey">{{ field.help_text }}</small>
                            {% endif %}
                            {% if field.help_text == "この項目は必須です。半角アルファベット、半角数字、@/./+/-/_ で150文字以下にしてください。" %}
                            <small style="color: grey">30文字以下にしてください。</small>
                            {% endif %}
                        {% endif %}
                        <!--エラー発生時のテキストerrorsを出力-->
                        {% for error in field.errors %}
                            <p style="color: red">{{ error}}</p>
                        {% endfor %}
                    </p>
                    {% endfor %}
                    <p style="color:red">
                        ※メールアドレスはパスワードをリセットする際に必要になりますので、登録をお願いします。
                    </p>
                    <!--Sign upボタンを出力-->
                    <input type="submit" value="Sign up">
                </form>
                <!--トップページのリンクテキスト-->
                <br>
                <p><a href="{% url 'photo:index' %}">
                    登録をやめてトップページに戻る</a>
                </p>
            </div>
        </div>
    </div>
    {% endblock %}

accounts/templates/signup_success.html
{% extends 'base.html' %}

{%block title %}Registration Complete{% endblock %}

    {% block contents %}
    {% load static %}

    <div class="container text-center">
        <div class="row">
            <div class="col py-4">
                <br>
                    <h3>登録が完了しました</h3>
                <br>
                <p><a href="{% url 'accounts:login' %}"><font size = "5"> <img src={% static "img/ログインはこちら.svg" %} alt="ロゴの表示" width="150" height="50"></font></a><p>
            </div>
        </div>
    </div>

    {% endblock %}