accounts/urls.py
from django.urls import path
# viewsモジュールをインポート
from . import views
from django.contrib.auth import views as auth_views

# URLパターンを逆引きできるように名前を付ける
app_name = 'accounts'

# URLパターンを登録するための変数
urlpatterns = [
    # サインアップページのビューの呼び出し
    #「http(s)://<ホスト名>/signup/」へのアクセスに対して、
    # viewsモジュールのSignUpViewをインスタンス化する
    path('signup/',
         views.SignUpView.as_view(),
         name = 'signup'),
    
    # サインアップ完了ページのビューの呼び出し
    # 「http(s)://<ホスト名>/signup_success/」へのアクセスに対して、
    # viewsモジュールのSignUpSuccessView.as_viewをインスタンス化する

    path('signup_success/',
         views.SignUpSuccessView.as_view(),
         name = 'signup_success'),

     # ログインページの表示
     #「http(s)://<ホスト名>signup/」へのアクセスに対して、
     # django.contrib.auth.views.LoginViewをインスタンス化して
     # ログインページを表示する
     path('login/',
          auth_views.LoginView.as_view(template_name = 'login.html'),
          name = 'login'
          ),

     # ログアウトを実行
     #「http(s)://<ホスト名>logout/」へのアクセスに対して、
     # django.contrib.auth.views.LogoutViewをインスタンス化して
     # ログアウトさせる
     path('logout/',
          auth_views.LogoutView.as_view(template_name = 'logout.html'),
          name = 'logout'
          ),
]

photo/urls.py
from django.urls import path
from . import views

#URLパターンを逆引きできるように名前を付ける
app_name = 'photo'

#URLパターンを登録する変数
urlpatterns = [
    #photoアプリへのアクセスはviewモジュールのIndexViewを実行
    path('', views.IndexView.as_view(), name='index'),

    #p446で追加
    #写真投稿ページへのアクセスはviewsモジュールのCreatePhotoViewを実行
    path('post/', views.CreatePhotoView.as_view(), name='post'),

    #p450で追加
    #投稿完了ページへのアクセスはviewsモジュールのPostSuccessViewを実行
    path('post_done/',
         views.PostSuccessView.as_view(),
         name='post_done'),
    
    # カテゴリ一覧ページ
    # photos/<Categorysテーブルのid値>にマッチング
    # <int:category>は辞書{category: id(int)}としてCategoryViewに渡される
    path('photos/<int:category>',
         views.CategoryView.as_view(),
         name = 'photos_cat'
        ),
    
    path('user-list/<int:user>',
        views.UserView.as_view(),
        name = 'user_list'
        ),

    #詳細ページ
    #photo-detail/<Photo Postsテーブルのid値>にマッチング
    #<int:pk>は辞書{pk: id(int)}としてDetailViewに渡される
    path('photo-detail/<int:pk>',
         views.DetailView.as_view(),
         name = 'photo_detail'
        ),
    
    # マイページ
    # mypage/へのアクセスはmypageViwを実行
    path('mypage/', views.MypageView.as_view(), name = 'mypage'),

    #URLを登録する変数

    #投稿写真の削除
    #photo/<Photo postsテーブルのid値>/delete/にマッチング
    #<int:pk>は{pk: id(int)}としてDetailViewに渡される
    path('photo/<int:pk>/delete/',
         views.PhotoDeleteView.as_view(),
         name = 'photo_delete'
        ),

]

photoproject/urls.py
from django.contrib import admin
from django.urls import path ,include
#from django.urls.conf import include #include追加

# auth.viewsをインポートしてauth_viewという名前で利用する
from django.contrib.auth import views as auth_views
#settingsを追加
from django.conf import settings
#staticを追加
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    
    #photo.urlsへのURLパターン
    path('', include('photo.urls')),

    path('', include('accounts.urls')),

    # パスワードリセットのためのURLパターン
    # PasswordResetConfigViewがプロジェクトのurls.pyを参照するのでここに記載
    # パスワードリセット申し込みページ
    path('password_reset/',
         auth_views.PasswordResetView.as_view(
             template_name = "password_reset.html"),
             name = 'password_reset'),
    
    # メール送信完了ページ
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name = "password_reset_sent.html"),
             name = 'password_reset_done'),
    
    # パスワードリセットページ
    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(
             template_name = "password_reset_form.html"),
             name = 'password_reset_confirm'),
    
    # パスワードリセット完了ページ
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name = "password_reset_done.html"),
             name = 'password_reset_complete'),
    
]

urlpatterns += static(
    #MEDIA_URL = 'media/'
    settings.MEDIA_URL,
    #MEDIA_ROOTにリダイレクト
    document_root=settings.MEDIA_ROOT
)

photo/models.py
from django.db import models

# accountsアプリのmodelsモジュールからCustomUserをインポート
from accounts.models import CustomUser

class Category(models.Model):
    '''投稿する写真のカテゴリを管理するモデル
    '''
    # カテゴリ名のフィールド
    title = models.CharField(
    verbose_name='カテゴリ', #フィールドのタイトル
    max_length=20)
    
    def __str__(self):
        '''オブジェクトを文字列に変更して返す

        Returns(str):カテゴリ名
        '''
        return self.title

class PhotoPost(models.Model):
    '''投稿されたデータを管理するモデル
    '''
    # CustomUserモデル（のuser_id）とPhotoPostモデルを１対多の関係で結びつける
    # CustomUserが親でPhotoPostがこの関係となる
    user = models.ForeignKey(
      CustomUser,
      #フィールドのタイトル
      verbose_name='ユーザー',
      #ユーザーを削除する場合はそのユーザーの投稿データもすべて削除する
      on_delete=models.CASCADE
      )
    category = models.ForeignKey(
      Category,
      #フィールドのタイトル
      verbose_name='カテゴリ',
      #カテゴリに関連付けられた投稿データが存在する場合は、そのカテゴリを削除できないようにする
      on_delete=models.PROTECT
      )
    #タイトル用のフィールド
    title = models.CharField(
        verbose_name='タイトル',#フィールドのタイトル
        max_length=30  #最大文字数は200
        )
#コメント用のフィールド
    comment = models.TextField(
        verbose_name='コメント', #フィールドのタイトル
        blank=True,            #フィールド値の設定は必須でない
        )
    #イメージのフィールド1
    image1 = models.ImageField(
        verbose_name='イメージ1', #フィールドのタイトル
        upload_to = 'photos'     #MEDIA_ROOT以下のphotosにファイルを保存
    )
    #イメージのフィールド2
    image2 = models.ImageField(
        verbose_name='イメージ2', #フィールドのタイトル
        upload_to = 'photos',  #MEDIA_ROOT以下のphotosにファイルを保存
        blank=True,            #フィールド値の設定は必須でない
        null=True              #データベースにnullが保存されることを許容
        )
    #投稿日時のフィールド
    posted_at = models.DateTimeField(
        verbose_name='投稿日時', #フィールドのタイトル
        auto_now_add=True  #日時を自動追加
        )
    
    def __str__(self):
        '''オブジェクトを文字列に変更して返す

        Returns(str):カテゴリ名
        '''
        return self.title



photo/forms.py
from django.forms import ModelForm
from .models import PhotoPost

class PhotoPostForm(ModelForm):
   '''ModelFormのサブクラス
   '''
   class Meta:
        '''ModelFormのインナークラス

        Attributes:
         model:モデルのクラス
         fields:フォームで使用するモデルのフィールドを指定
        '''
        #以下model、fieldsを変更　削除ではない
        model = PhotoPost
        fields = ['category','title','comment','image1','image2']

photo/views.py
from django.shortcuts import render
#P455   ListViewを追加
#django.views.genericからTemplateView,ListViewをインポート
from django.views.generic import TemplateView, ListView
#django.views.genericからCreateViewをインポート
from django.views.generic import CreateView
#django.urlsからreverse_lazyをインポート
from django.urls import reverse_lazy
#formsモジュールからPhotoPostFormをインポート
from .forms import PhotoPostForm
#method_decoratorをインポート
from django.utils.decorators import method_decorator
#login_requiredをインポート
from django.contrib.auth.decorators import login_required
#P455
#modelsモジュールからモデルPhotoPostをインポート
from .models import PhotoPost
#django.views.genericからDetailViewをインポート
from django.views.generic import DeleteView

#P455　　(TemplateView)から(ListView)に変更
class IndexView(ListView):
    '''トップビューのビュー
    '''
    #index.htmlをレンダリングする
    template_name = 'index.html'
    #P455
    #モデルBlogPostのオブジェクトにorder_by()を適用して投稿日時の降順で並べ替える
    queryset = PhotoPost.objects.order_by('-posted_at')
    #P464
    #1ページに表示するレコードの件数
    paginate_by = 12

#デコレーターにより、CreatePhotoViewへのアクセスはログインユーザーに限定される
# ログイン状態でなければsetting.pyのLOGIN_URLにリダイレクトされる 
@method_decorator(login_required,name='dispatch')
class CreatePhotoView(CreateView):
  '''写真投稿のビュー

  PhotoPostFormで定義されているモデルとフィールドと連携して
  投稿データをデータベースに登録する

  Attributes:
    form_class:モデルとフィールドが登録されたフォームクラス
    template_name:レンダリングするテンプレート
    success_url:データベースへの登録完了後へのリダイレクト先
  '''

 #forms.pyのPhotoPostFormをフォームクラスとして登録
  form_class = PhotoPostForm
  #レンダリングするテンプレート
  template_name = "post_photo.html"
  #フォームデータ登録完了後のレンダリング先
  success_url = reverse_lazy('photo:post_done')

  def form_valid(self,form):
    #ファームデータの登録をここで行う 
    #commit=Falseにしてポストされたデータを取得
    postdata = form.save(commit=False)
    #投稿ユーザーのIDを取得してモデルのユーザーフィールドに格納
    postdata.user = self.request.user
    #投稿データをデータベースに登録
    postdata.save()
    #戻り値はスーパークラスのform_validの戻り値
    return super().form_valid(form)

#p449で追加
class PostSuccessView(TemplateView):
  '''投稿完了ページのビュー

      Attributes:
        template_name:レンダリングするテンプレート
  ''' 
  #index.htmlをレンダリングする
  template_name = 'post_success.html'

  

class CategoryView(ListView):
    '''カテゴリページのビュー

    Attributes:
        template_name: レンタリングするテンプレート
        paginate_by: 1ページに表示するレコードの件数
    '''
    # index.htmlをレンタリングする
    template_name = 'index.html'
    # 1ページに表示するレコードの件数
    paginate_by = 12

    def get_queryset(self):
        '''クエリを実行する

        self.keeargsの取得が必要なため、クラス変数querysetではなく、
        get_queryset()オーバーライド二よりクエリを実行する

        Returns:
            クエリによって取得されたレコード
        '''
        # self.kwargsでキーワードの辞書を取得し、
        # categoryキーの値(Categoryテーブルのid)を取得
        category_id = self.kwargs['category']
        # filter(フィールド名=id)で絞り込む
        categories = PhotoPost.objects.filter(
            category = category_id).order_by('-posted_at')
        # クエリによって取得されたレコードを返す
        return categories

class UserView(ListView):
    '''ユーザー投稿一覧ページのビュー
    Attributes:
        template_name: レンタリングするテンプレート
        paginate_by: 1ページに表示するレコードの件数
    '''
    # index.htmlをレンタリングする
    template_name = 'index.html'
    #１ページに表示するレコードの件数
    paginate_by = 12

    def get_queryset(self):
        '''クエリを実行する
        self.kwargsの取得が必要なため、クラス変数querysetではなく、
        get_queryset()オーバーライドによりクエリを実行する
        
        Returns:クエリによって取得されたレコード
        '''
        # self.kwargsでキーワードの辞書を取得し、
        # userキーの値（ユーザーテーブルのid）を取得
        user_id = self.kwargs['user']
        # filter（フィールド名=id）で絞り込む
        user_list = PhotoPost.objects.filter(
            user=user_id).order_by('-posted_at')
        # クエリによって取得されたレコードを返す
        return user_list
    
#UserViewの後
class DetailView(DeleteView):

    '''詳細ページのビュー

    投稿記事の詳細を表示するのでDetailViewを継承する
    Attributes:
    template_name:レンダリングするテンプレート
    model:モデルのクラス
    '''
    #post.htmlをレンダリングする
    template_name = 'detail.html'
    #クラス変数modelにモデルBlogPostを設定
    model = PhotoPost

class MypageView(ListView):
    '''マイページのビュー

    Attributes:
        template_name: レンタリングするテンプレート
        paginate_by: １ページに表示するレコードの件数
    '''
    # mypage.htmlをレンタリングする
    template_name = 'mypage.html'
    # 1ページに表示するレコードの件数
    paginate_by = 12

    def get_queryset(self):
        '''クエリを実行する

        self.kwargsの取得が必要なため、クラス変数querysetではなく、
        get_queryset()のオーバーライドによりクエリを実行する

        Returns:
           クエリによって取得されたコード
        '''
        # 現在ログインしているユーザ名はHttpRequest.userに格納されている
        # filter(userフィールド=userオブジェクト)で絞り込む
        queryset = PhotoPost.objects.filter(
            user = self.request.user).order_by('-posted_at')
        #クエリによって取得されたレコードを返す
        return queryset

#MypageViewの続き
class PhotoDeleteView(DeleteView):
    '''レコードの削除を行うビュー

    Attributes:
      model:モデル
      template_name:レンダリングするテンプレート
      paginate_by:1ページに表示するレコードの件数
      success_url:削除完了後のリダイレクト先のURL
    '''
    # 操作の対象はPhotoPostモデル
    model = PhotoPost
    # photo_delete.htmlをレンダリングする
    template_name = 'photo_delete.html'
    # 処理完了後にマイページにリダイレクト
    success_url = reverse_lazy('photo:mypage')

    def delete(self, request, *args, **kwargs):
        '''レコードの削除を行う

        parameters:
            self:PhotoDeleteViewオブジェクト
            request:WSGIRequest(HttpRequest)オブジェクト
            args:引用として渡される辞書(dict)
            kwargs:キーワード付きの辞書(dict)
                   {'pk':21}のようにレコードのidが渡される
        
        Returns:
          HttpResponseRedirect{success_url}を返して
          success_urlにリダイレクト
        '''
        #　スーパークラスのdelete()を実行
        return super().delete(request, *args, **kwargs)

photo/templates/detail.html
<style>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</style>

<!--ベーステンプレートを適用する-->
{% extends 'base.html' %}
<!--ヘッダー情報のページタイトルを設定する-->
{% block title %}写真の詳細{% endblock %}

        {% block contents %}
        {% load static %}
        <!--Bootstrapのグリッドシステム-->
        <br>
        <div class="text-center">
            <!--行を配置-->
            <div class="row">
                <!--列の左右に余白offset-1を入れる-->
                <div>
                    
                    <!--タイトル-->
                    <h2>{{object.title}}</h2>
                    <!--コメント-->
                    <p>{{object.comment}}</p>
                    <br>
                    <!--投稿日時-->
                    <p>{{object.posted_at}}に投稿</p>
                    <!--1枚目の写真-->
                    <p><img class = "img-size" src="{{object.image1.url}}"></img></p>
                    <!--2枚目の写真が投稿されていたら表示する-->
                    {% if object.image2 %}
                      <p><img class = "img-size" src="{{object.image2.url}}"></img></p>
                    {% endif %}

                   <!--投稿写真がログイン中のユーザーのものであれば削除ボタンを表示-->
                   {% if request.user == object.user %}
                   <form method="POST">
                   <!--リンク先のURL
                　　　　photo/<Photo postsテーブルのid値>/delete/-->
                   <a href="{% url 'photo:photo_delete' object.pk %}">
                    <img src={% static "img/削除する.svg" %} alt="ロゴの表示" width="150" height="55">    
                </a>
                   {% endif %}

                </div>
            </div>
        </div>
        {% endblock %}                    

photo/templates/photos_title.html
{% load static %}
<style>
  /*カルーセル機能の追加*/
    
      * {
        box-sizing: border-box;
        list-style: none;
        padding: 0;
        margin: 0;
      }
      h1 {
      margin-bottom: 100px;
      }
      h2 {
      margin-bottom: 50px;
      }
      /* スライドする要素 */
      .content {
      width: 300px;
      height: 300px;
      }
      .content:nth-child(1) {
      background-color: #9acd32;
      }
      .content:nth-child(2) {
      background-color: #729925;
      }
      .content:nth-child(3) {
      background-color: #ccad00;
      }
      .content:nth-child(4) {
      background-color: green;
      }
      /* スライドレールの枠 */
      .wrap {
      overflow: hidden;
      display: flex;
      align-items: center;
      height: 340px;
      
      }
      /* content4つをまとめたスライドブロック */
      .slideshow {
      display: flex;
      -webkit-animation: loop-slide 18s infinite linear 1s both;
      animation: loop-slide 18s infinite linear 1s both;
      }
      @-webkit-keyframes loop-slide {
      from {
          transform: translateX(0);
      }
      to {
          transform: translateX(-100%);
      }
      }
      @keyframes loop-slide {
      from {
          transform: translateX(0);
      }
      to {
          transform: translateX(-100%);
      }
      }
      /* ホバー時に動きを止める（パターン2・3）*/
      .slide-paused:hover .slideshow {
      -webkit-animation-play-state: paused;
      animation-play-state: paused;
      }
      /* ホバー時の装飾（パターン3） */
      .content-hover {
      transition: all 0.2s;
      margin-right: 20px;
      }
      .content-hover:hover {
      transform: translateY(-20px);
      border-radius: 0 10%;
      box-shadow: 0 3px 10px 0 #333;
      opacity: 0.8;
      cursor: pointer;
      }
      ul {
        padding-left: 0rem!important;
      }

      /*カルーセルここまで*/
</style>  
<section class=" text-center ">
  <div class="">

    <div>
      <!-- カボスの画像の挿入 -->
      <li style="background-image: url( '{% static 'img/かぼす.png' %}' );" width = "100%">
        <br>
        <div class="fw-light"><font size = "8"face = "Comic Sans MS";>Oitagram</font></div>
        <p class="lead "_ngcontent-ng-c3722798491 dir="auto" 
        class="text-container" style="font-family: 'Zen Maru Gothic', sans-serif";>
        <font size = "4">大分県に関する写真の投稿をお待ちしています！</font></p>

        <p>
        {% if user.is_authenticated %}
        <a href="{% url 'photo:post' %}">
          <img src={% static "img/投稿する.svg" %} alt="ロゴの表示" width="100" height="45"></a>
        <a href="{% url 'accounts:logout' %}">
          <img src={% static "img/ログアウト.svg" %} alt="ロゴの表示" width="100" height="45"></a>
        {% else %}
        <a href="{% url 'accounts:signup' %}" >
          <img src={% static "img/今すぐサインアップ.svg" %} alt="ロゴの表示" width="160" height="45"></a>
        <a href="{% url 'accounts:login' %}"> 
          <img src={% static "img/登録済みの方はログイン.svg" %} alt="ロゴの表示" width="170" height="40"></a>
        {% endif %}
        </p>
    </div>
    
    <div class="wrap">
      <ul class="slideshow">
          <li class="content">

            <!-- オブジェクトリストの1番目を取得 -->
            {% if object_list.0.image1.url %}
            <img src="{{ object_list.0.image1.url }}"
            class="bd-placeholder-img card-img-top caruuseru" 
            which="100%" height="300"
            xmlns="http://www.w3.org/2000/svg"
            role="img" aria-label="Placeholder: Thumbnail"
            preserveAspectRatio="xMidYMid slice"
            focusable="false"
            onclick="location.href='{% url 'photo:photo_detail' object_list.0.pk %}'">
            <title>Placeholder</title>
            <rect width="100%" height="100%" fill="#55595c"/>
            {% endif %}

          </img>
          </li>
          <li class="content">
            <!-- オブジェクトリストの2番目を取得 -->
            {% if object_list.1.image1.url %}
            <img src="{{ object_list.1.image1.url }}"
            class="bd-placeholder-img card-img-top caruuseru" 
            which="100%" height="300"
            xmlns="http://www.w3.org/2000/svg"
            role="img" aria-label="Placeholder: Thumbnail"
            preserveAspectRatio="xMidYMid slice"
            focusable="false"
            onclick="location.href='{% url 'photo:photo_detail' object_list.1.pk %}'">
            <title>Placeholder</title>
            <rect width="100%" height="100%" fill="#55595c"/>
            {% endif %}

          </img>
          </li>
          <li class="content">
            <!-- オブジェクトリストの3番目を取得 -->
            {% if object_list.2.image1.url %}
            <img src="{{ object_list.2.image1.url }}"
            class="bd-placeholder-img card-img-top caruuseru" 
            which="100%" height="300"
            xmlns="http://www.w3.org/2000/svg"
            role="img" aria-label="Placeholder: Thumbnail"
            preserveAspectRatio="xMidYMid slice"
            focusable="false"
            onclick="location.href='{% url 'photo:photo_detail' object_list.2.pk %}'">
            <title>Placeholder</title>
            <rect width="100%" height="100%" fill="#55595c"/>
            {% endif %}

          </img>
          </li>
          <li class="content">
            <!-- オブジェクトリストの4番目を取得 -->
            {% if object_list.3.image1.url %}
            <img src="{{ object_list.3.image1.url }}"
            class="bd-placeholder-img card-img-top caruuseru"
            which="100%" height="300"
            xmlns="http://www.w3.org/2000/svg"
            role="img" aria-label="Placeholder: Thumbnail"
            preserveAspectRatio="xMidYMid slice"
            focusable="false"
            onclick="location.href='{% url 'photo:photo_detail' object_list.3.pk %}'">
            <title>Placeholder</title>
            <rect width="100%" height="100%" fill="#55595c"/>
            {% endif %}

          </img>
          </li>
      </ul>
      <!-- カルーセル２個目 -->
      <ul class="slideshow">
        <li class="content">

          <!-- オブジェクトリストの1番目を取得 -->
          {% if object_list.0.image1.url %}
          <img src="{{ object_list.0.image1.url }}"
          class="bd-placeholder-img card-img-top caruuseru" 
          which="100%" height="300"
          xmlns="http://www.w3.org/2000/svg"
          role="img" aria-label="Placeholder: Thumbnail"
          preserveAspectRatio="xMidYMid slice"
          focusable="false"
          {% comment %} <!--ばぐにするところ--> {% endcomment %}
          onclick="location.href='{% url 'photo:photo_detail' object_list.0.pk %}'">
          <rect width="100%" height="100%" fill="#55595c"/>
          {% endif %}

        </img>
        </li>
        <li class="content">
          <!-- オブジェクトリストの2番目を取得 -->
          {% if object_list.1.image1.url %}
          <img src="{{ object_list.1.image1.url }}"
          class="bd-placeholder-img card-img-top caruuseru" 
          which="100%" height="300"
          xmlns="http://www.w3.org/2000/svg"
          role="img" aria-label="Placeholder: Thumbnail"
          preserveAspectRatio="xMidYMid slice"
          focusable="false"
          onclick="location.href='{% url 'photo:photo_detail' object_list.1.pk %}'">
          <title>Placeholder</title>
          <rect width="100%" height="100%" fill="#55595c"/>
          {% endif %}

        </img>
        </li>
        <li class="content">
          <!-- オブジェクトリストの3番目を取得 -->
          {% if object_list.2.image1.url %}
          <img src="{{ object_list.2.image1.url }}"
          class="bd-placeholder-img card-img-top caruuseru" 
          which="100%" height="300"
          xmlns="http://www.w3.org/2000/svg"
          role="img" aria-label="Placeholder: Thumbnail"
          preserveAspectRatio="xMidYMid slice"
          focusable="false"
          onclick="location.href='{% url 'photo:photo_detail' object_list.2.pk %}'">
          <title>Placeholder</title>
          <rect width="100%" height="100%" fill="#55595c"/>
          {% endif %}

        </img>
        </li>
        <li class="content">
          <!-- オブジェクトリストの4番目を取得 -->
          {% if object_list.3.image1.url %}
          <img src="{{ object_list.3.image1.url }}"
          class="bd-placeholder-img card-img-top caruuseru"
          which="100%" height="300"
          xmlns="http://www.w3.org/2000/svg"
          role="img" aria-label="Placeholder: Thumbnail"
          preserveAspectRatio="xMidYMid slice"
          focusable="false"
          onclick="location.href='{% url 'photo:photo_detail' object_list.3.pk %}'">
          <title>Placeholder</title>
          <rect width="100%" height="100%" fill="#55595c"/>
          {% endif %}

        </img>
        </li>
      </ul>
      <ul class="slideshow">
        <li class="content">

          <!-- オブジェクトリストの1番目を取得 -->
          {% if object_list.0.image1.url %}
          <img src="{{ object_list.0.image1.url }}"
          class="bd-placeholder-img card-img-top caruuseru" 
          which="100%" height="300"
          xmlns="http://www.w3.org/2000/svg"
          role="img" aria-label="Placeholder: Thumbnail"
          preserveAspectRatio="xMidYMid slice"
          focusable="false"
          onclick="location.href='{% url 'photo:photo_detail' object_list.0.pk %}'"> 
          <title>Placeholder</title>
          <rect width="100%" height="100%" fill="#55595c"/>
          {% endif %}

        </img>
        </li>
        <!-- カルーセル3個目 -->
        <li class="content">
          <!-- オブジェクトリストの2番目を取得 -->
          {% if object_list.1.image1.url %}
          <img src="{{ object_list.1.image1.url }}"
          class="bd-placeholder-img card-img-top caruuseru" 
          which="100%" height="300"
          xmlns="http://www.w3.org/2000/svg"
          role="img" aria-label="Placeholder: Thumbnail"
          preserveAspectRatio="xMidYMid slice"
          focusable="false">
          <!--onclick="location.href='{% url 'photo:photo_detail' object_list.1.pk %}'"-->
          <title>Placeholder</title>
          <rect width="100%" height="100%" fill="#55595c"/>
          {% endif %}

        </img>
        </li>
        <li class="content">
          <!-- オブジェクトリストの3番目を取得 -->
          {% if object_list.2.image1.url %}
          <img src="{{ object_list.2.image1.url }}"
          class="bd-placeholder-img card-img-top caruuseru" 
          which="100%" height="300"
          xmlns="http://www.w3.org/2000/svg"
          role="img" aria-label="Placeholder: Thumbnail"
          preserveAspectRatio="xMidYMid slice"
          focusable="false"
          onclick="location.href='{% url 'photo:photo_detail' object_list.2.pk %}'">
          <title>Placeholder</title>
          <rect width="100%" height="100%" fill="#55595c"/>
          {% endif %}

        </img>
        </li>
        <li class="content">
          <!-- オブジェクトリストの4番目を取得 -->
          {% if object_list.3.image1.url %}
          <img src="{{ object_list.3.image1.url }}"
          class="bd-placeholder-img card-img-top caruuseru"
          which="100%" height="300"
          xmlns="http://www.w3.org/2000/svg"
          role="img" aria-label="Placeholder: Thumbnail"
          preserveAspectRatio="xMidYMid slice"
          focusable="false"
          onclick="location.href='{% url 'photo:photo_detail' object_list.3.pk %}'">
          <title>Placeholder</title>
          <rect width="100%" height="100%" fill="#55595c"/>
          {% endif %}

        </img>
        </li>
      </ul>
  </div> 

  </div>
</section>